# Generated by Django 5.1.5 on 2025-04-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
